kind: Secret
apiVersion: v1
metadata:
  name: test-secret
type: Opaque
data:
  latest-test-argocd-vault-plugin: <path:ossp-vault#ossp-sample-secrets>
  old-test-argocd-vault-plugin: <path:ossp-vault#ossp-sample-secrets#89845f17012d44c5b787c1f4bb752093>
