kind: Secret
apiVersion: v1
metadata:
  name: test-secret
type: Opaque
data:
  latest-test-argocd-vault-plugin: <path:ossp-vault#test-argo-plugin-access>
  old-test-argocd-vault-plugin: <path:ossp-vault#test-argo-plugin-access>
